### PR TITLE
debuged the fetch and added further style

### PR DESCRIPTION
**Pull request by Rod-Freedom**
I fixed the fetch Pokemon list function. It now works with a handmade loop of a single function that calls itself each time. I also added other functions that will be called after the fetch to render the pokemons. Lastly, I added more styling to the index.html. The left PokeCard is now finished.

### CODE REVIEW

**Comment by Marcoeliasb** [comment]
nice

**Comment by Karimegtz** [comment]
Great work

**Review by Karimegtz — COMMENTED** [review]
Great work

**Review by Karimegtz — APPROVED** [review]
Great work

**Pull request merged**
