### PR TITLE
added file structure and index.html half way with style

### PR DESCRIPTION
**Pull request by Rod-Freedom**
I added the whole file structure and the index.html structure. Tailwind has been added. The index is half way done in terms of design.

### CODE REVIEW

**Comment by Karimegtz** [comment]
Great

**Comment by Marcoeliasb** [comment]
nice job

**Comment by Marcoeliasb** [comment]
nice job

**Comment by Karimegtz** [comment]
Nice

**Comment by Karimegtz** [comment]
Nice

**Review by Karimegtz — COMMENTED** [review]
Nice

**Review by Karimegtz — APPROVED** [review]
NICE

**Review by Marcoeliasb — APPROVED** [review]
nice job

**Comment by AlejnadroVill** [comment]
Hey! Nice job rod:)

**Pull request merged**
